### ISSUE TITLE
Shock layer amplified underwater

### ISSUE THREAD

**Issue by TerrificTrifid** [Outer-Wilds-New-Horizons/new-horizons#245]
### What Happened?

When going underwater, shock layer is seemingly amplified, so it ramps up to flames way quicker. Might have to do with fluid density, and maybe GD has a solution.

### What was supposed to happen?

It should just disappear.

**Comment by MegaPiggy** [comment]
Giant's Deep also has the shock layer underwater so I'm not sure why you want it to disappear.

**Comment by TerrificTrifid** [comment]
Well you're not supposed to go that fast normally, but okay, make it like that then I guess.

**Comment by JohnCorby** [comment]
does this actually happen? it seems normal to me and this hasnt been talked about in a while

**Comment by MegaPiggy** [comment]
it might. I'll look into it when I have time.

**Comment by MegaPiggy** [comment]
Definitely has to do with fluid density.

Atmospheric shock layers (every shock layer that isn't from a star) uses `FluidDetector`'s `GetRelativeFluidVelocity` which is essentially just the sum of the method `GetPointFluidVelocity`'s result for every fluid volume you are in.

I think Giant's Deep is special because it uses its own fluid volume `SphereOceanFluidVolume` that overrides `GetPointFluidVelocity`.

**Comment by JohnCorby** [comment]
it does the same thing as the overridden thing, just with extra current stuff to it. the density of gd and nh water is identical now so it should behave the exact same way now
