### ISSUE TITLE
Borked Map Lighting

### ISSUE THREAD

**Issue by mrwallace888** [Outer-Wilds-New-Horizons/new-horizons#335]
### What Happened?

Objects behave like they're lit below when viewed in the map.

**Comment by MegaPiggy** [comment]
I don't know what this means

**Comment by MegaPiggy** [comment]
Could you show a picture of what you mean?

**Comment by MegaPiggy** [comment]
![image](https://user-images.githubusercontent.com/34462599/187781862-5bd3855d-e971-4dcb-9726-a7b5fc105874.png)

**Comment by JohnCorby** [comment]
this happens because FaceActiveCamera, the script that controls the directional lights, makes the lights point straight up when you're in map mode. i think it doesnt look broken in base game because of the directional light hacks they do to shaders. if we used shader replacement on the clouds they'll potentially look more correct
