### ISSUE TITLE
Small bramble nodes obstruct preview fog lights

### ISSUE THREAD

**Issue by coderCleric** [Outer-Wilds-New-Horizons/new-horizons#574]
### What Happened?

It seems like shrinking bramble nodes can cause the internal geometry to get in the way of the actual light. This makes it so that the light can only be seen from specific angles. It's definitely the node geometry itself, as disabling the collider of the node causes the light to reappear.

### What was supposed to happen?

The light should be viewable from most angles that see the internal fog, especially head-on

### Platform

Steam

### Mods

```Markdown
Just NH and my custom addon
```

**Comment by xen-42** [comment]
Can you provide an image

**Comment by xen-42** [comment]
Nvm, anyway I can't figure out why this happens. It's totally FogLight.UpdateFogLight which does two raycasts, just not sure where that's going wrong. Gonna call this a vanilla bug and say the nodes ought to have had a better mesh (it happens to Vanilla nodes but it's less noticeable since they're so large).
