### ISSUE TITLE
Ship HUD marker fails to display when spawning on center of universe

### ISSUE THREAD

**Issue by coderCleric** [Outer-Wilds-New-Horizons/new-horizons#648]
### What Happened?

I spawned directly into a Bramble dimension, and the ship HUD marker failed to display. The spawn point was also in the center of the system. The HUD marker did not show up as I changed what dimension I was in, although I was unable to test what happens if the player leaves all dimensions.

### What was supposed to happen?

The ship HUD marker should have still appeared.

### Platform

None

### Mods

```Markdown
Only what mods were necessary to run a NH addon.
```

### Logs

```Shell
There do not seem to be any relevant errors.
```

**Comment by xen-42** [comment]
Lot going on here:

The bramble dimension is only active because its the center of the universe (those cannot be made inactive else it messes up a bunch of stuff)

We need to just natively support spawning into a bramble dimension, so putting the player and ship into the node and its relevant volumes and activating it.

On a similar note having the ship and player spawn in different places also isn't currently supported fully, but once it is we'd have to suspend the ship if it was spawned in a dimension while the player wasnt

**Comment by coderCleric** [comment]
Did a bit of extra testing, and confirmed that this specific HUD bug happens even without a bramble dimension, as long as the ship spawns in the center of the system. This bug also seems to be accompanied by the particle effects for damaged oxygen and fuel tanks being active, despite those modules being intact.

**Comment by JohnCorby** [comment]
nuh uh
