### ISSUE TITLE
"canScoutExit" field for Bramble dimensions

### ISSUE THREAD

**Issue by CrypticBird** [Outer-Wilds-New-Horizons/new-horizons#680]
### Feature

Currently with NH, firing a scout through a dimension exit just reflects it back at you. In the base-game this sometimes is the case, but in other dimensions (eg. Feldspar's Dimension), the scout can exit normally, as the player can. A "canScoutExit" field that toggles this behavior would be very handy.

### Context

The only caveat to this is that having a scout exit to a node _in space_ (rather than to a node within another dimension) might not work. This should probably be stated in the schema, were this feature added.

**Comment by xen-42** [comment]
Turns out in vanilla the scout never exits the same way the player does, it's always deliberately reflected back into the node it just came out of. Sometimes this results in the scout being reflected back to the player that sent it, but sometimes the node that you come out of links to an entirely different dimension, leading to some confusion about what was actually happening.

Since NH is behaving the same way vanilla does, I'm closing this. I'll implement the requested feature as custom code in the Extinction mod Bird is working on instead.
