### ISSUE TITLE
Circle from breathing signal stuck at the Eye

### ISSUE THREAD

**Issue by coderCleric** [Outer-Wilds-New-Horizons/new-horizons#925]
### What Happened?

When going through the Eye sequence, walking close to your other self with your signalscope out will cause them and their signal to disappear, but the circle on the UI will stay until you talk to Esker and activate Riebeck's area. 

I've checked and this happens with the mod list below, but doesn't if NH alone is removed.

### What was supposed to happen?

When your clone disappears, the UI element should deactivate.

### Platform

Steam

### Mods

```Markdown
NH and dependencies
Cheat and Debug Menu
Unity Explorer
```

### Logs

```Shell
I didn't notice anything unusual.
```

**Comment by Hawkbat** [comment]
This issue occurs because the `SignalScopeReticleController` that controls the signalscope reticle brackets normally creates a reticle for every single signal in the game using the list from `Locator.GetAudioSignals()`, but New Horizons patches that list to only include currently active signals. When the clone's breathing signal is deactivated, the reticle created for it is 'orphaned' and never updated again to disable it.
